### ISSUE TITLE
Getting "Sass Complie Error"

### ISSUE THREAD

**Issue by mischnu** [VineCode/Sass.novaextension#7] opened 2020-10-06 11:29 UTC
When saving, I see an error message saying:

> OptionParser::InvalidOption: invalid option: --error-css
> Use --trace for backtrace.

Any idea?

**Comment by vinecode-andy** [comment] 2020-10-16 14:41
Hi @mischnu , in the Terminal could you run `/usr/local/bin/sass --version` and let me know the output.

**Comment by mischnu** [comment] 2020-10-19 06:58
Hi @vinecode-andy, sure – it’s 1.27.0

**Comment by acafourek** [comment] 2020-10-27 13:35
Experienced the same today with fresh install and bare bones scss file. Confirmed the SCSS compiles with CodeKit and other tools.

When I run `/usr/local/bin/sass --version` in terminal, my output is `Ruby Sass 3.7.4`

**Comment by Fluffier** [comment] 2020-10-28 11:55
I'm having same problem. Nova and plugin fresh installed today.
My MacOS is 10.14.6 (Mojave), and output of `/usr/local/bin/sass --version` in terminal is `Sass 3.5.3 (Bleeding Edge)`

**Comment by jwssnr** [comment] 2020-11-13 13:14
Same here. macOS 10.15.7 and `Sass 3.5.5 (Bleeding Edge)`

**Comment by vinecode-andy** [comment] 2020-11-13 13:17
I have been able to re-product this and am working on an update. Will make it available ASAP.

**Comment by vinecode-andy** [comment] 2020-11-13 13:24
Hi All, 

I think the issue is that you are using the Ruby Sass rather than the Dart version. 

As per the Sass documentation "Ruby Sass has reached end of life and is now totally unmaintained. Please switch to Dart Sass or LibSass at your earliest convenience."

If you install via Brew (https://sass-lang.com/install) `sass --version` should give you the latest version 1.29.0.

Could you let me know if this resolves the issue.

**Comment by jwssnr** [comment] 2020-11-13 13:36
I’ll try. But the Version I get still is 3.5.5. Think I have to uninstall ruby sass first. But I don’t get how!

**Comment by vinecode-andy** [comment] 2020-11-13 13:40
Hey @jwssnr Did you update brew first with `brew update`

If you run `brew list sass/sass/sass` you should get something similar to /usr/local/Cellar/sass/1.29.0/bin/sass if the correct version is available.

**Comment by jwssnr** [comment] 2020-11-13 13:42
Yes. But if I’m running just `sass --version` I’m getting `Sass 3.5.1 (Bleeding Edge)`.

**Comment by vinecode-andy** [comment] 2020-11-13 13:47
@jwssnr I think that the old Ruby Sass package will be marked as outdated so a brew update and upgrade should replace it with the Dart version. `brew update && brew upgrade sass/sass/sass`

**Comment by vinecode-andy** [comment] 2020-11-13 13:58
It may also be that your brew installed version is not linked to the location /usr/local/bin/sass and / or that you have multiple versions. 

Usually brew will install to `/usr/local/Cellar/sass/1.29.0/bin/sass` you may need to use this path for the "Executable Path" in the extension Preferences. 

Running `/usr/local/Cellar/sass/1.29.0/bin/sass --version` will let you know if it is there.

**Comment by jwssnr** [comment] 2020-11-13 14:05
1.29.0 is running says the terminal. I also did this: `gem uninstall -i /Users/jwssnr/.rvm/gems/ruby-2.3.3@global sass
`. Now Nova says on save `/Users/(user)/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem sass (>= 0.a) (Gem::GemNotFoundException)
from /Users/jwssnr/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Seems like Nova still wants to run ruby sass.

**Comment by jwssnr** [comment] 2020-11-13 16:14
Thank you, Andy. With the "Executable Path" it works.

**Closed** 2020-11-13 16:45 UTC
